file_setting = "file"
upload_setting = "upload"
mean_setting = "mean"
json_setting = "json"
graphs_setting = "graphs"
top_regs_string = "top_regs"
flights_string = "flights"
mean_duration_string = "mean_duration"
peak_load_string = "peak_load"
mean_dynamic_string = "mean_dynamic"
rise_fall_string = "rise_fall"
day_act_string = "day_act"
empty_days_string = "empty_days"
flight_density_string = "flight_density"
failed_string = "failed"
mean_string = "mean"

message_string = "message"
unexpected_error_string = "Возникла непредвиденная ошибка"

